version: '3.7'

# Mantri is the only app where the database volumes are not designated as 'external'.
# This is because mantri initializes these volumes. All other apps must designate
# their database volumes as 'external'.
volumes:
    db_data:
        name: ohm_db
    db_data_backups:
        name: ohm_db_backups
    # node_modules:
    #     name: omm_node_modules

services:
    backend: &django
        build:
            context: .
            dockerfile: ./compose/dev/v1/django/Dockerfile
        image: omm_dev_backend
        depends_on:
            - db
            - cache
        volumes:
            - ./backend:/app
        env_file:
            - ./.envs/.dev/.django.v1
            - ./.envs/.dev/.postgres.v1
        ports:
            - "8000:8000"
        restart: always
        command: /start

    db:
        build:
            context: .
            dockerfile: ./compose/dev/v1/postgres/Dockerfile
        image: omm_dev_db
        volumes:
            - db_data:/var/lib/postgresql/data
            - db_data_backups:/backups
        env_file:
            - ./.envs/.dev/.postgres.v1
        restart: always

    cache:
        build:
            context: .
            dockerfile: ./compose/dev/v1/redis/Dockerfile
        image: omm_dev_cache
        env_file:
            - ./.envs/.dev/.redis.v1
        sysctls:
            net.core.somaxconn: '511'
        restart: always
