CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS ohm;

CREATE TABLE IF NOT EXISTS ohm.ohm_tenant (
    _id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dbname varchar(22) UNIQUE, -- generated by python shortuuid --
    name text NOT NULL,
    phone text NOT NULL,
    email text,
    adminuser text NOT NULL,
    adminpassword NOT NULL,
    user text NOT NULL,
    userpassword text NOT NULL,
    readuser text NOT NULL,
    readerpassword text NOT NULL
);
